import Head from 'next/head'
import { useRef, useState, useEffect} from 'react'
import styles from '../styles/Home.module.scss'
import Bio from '../components/Bio/Bio'
import ArrowDown from '../components/ArrowDown'
import SkillSection from '../components/Skills'
import Navbar from '../components/Navbar/Navbar'
import Contact from '../components/Contact/Contact'


import SkillSet from '../components/Skills/Skillset'
import { motion, scrollYProgress, AnimatePresence, useTransform, useViewportScroll, useMotionValue} from 'framer-motion'

export default function Home() {
  const { scrollYProgress } = useViewportScroll()
  const [currentPrecent, setCurrentPercent] = useState(null)
  const yRange = useTransform(scrollYProgress, [0, 1], [0, 100]);
  const skillSectionAnim = useTransform(scrollYProgress, [0, .68, 1], [.5, 1, 1])


  useEffect(
    () =>
        yRange.onChange((v) => {
            setCurrentPercent(Math.trunc(yRange.current))
        }),
    [yRange]
);

        console.log(currentPrecent)

  return (
    <div >
      <Head>
        <title>Bevan Tony Medrano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      <motion.div>
        <Navbar/>
      </motion.div>
      <main className={styles.main}>
        <div> 
        <motion.div initial='hidden' animate='visible' variants={{
          hidden:{
            scale:.5,
            opacity:0
          },
          visible:{
            opacity:1,
            scale:1,
            transition:{
              delay:.5
            }
          }
        }}>
          <Bio headshot='/DPTwitter.jpeg' 
            name='Bevan Tony Medrano' 
            role='FrontEnd Web Developer'
            email='medranobevantony@gmail.com'/>
        </motion.div>
        </div>
        <motion.div initial='hidden' animate='visible' variants={{
          hidden:{
            scale:3,
            opacity:0},
          visible:{
            opacity:1,
            scale:1,
          transition:{
              delay:1,
            }
          }
        }}>
            <ArrowDown/>
        </motion.div>
      </main>
      {/* <motion.div style={{scale:skillSectionAnim, opacity:skillSectionAnim}}> */}
        <SkillSection skillset={SkillSet}/>
      {/* </motion.div> */}

        <div>
          <Contact/>
        </div>

    </div>
    </div>
  )
}
