import Head from 'next/head'
import { useState, useEffect} from 'react'
import styles from '../styles/Home.module.scss'
import Landing from './Landing/Landing'
import { motion, scrollYProgress, AnimatePresence, useTransform, useViewportScroll, useMotionValue} from 'framer-motion'

export default function Home() {
  const { scrollYProgress } = useViewportScroll()
  const [currentPrecent, setCurrentPercent] = useState(null)
  const yRange = useTransform(scrollYProgress, [0, 1], [0, 100]);
  const skillSectionAnim = useTransform(scrollYProgress, [0, .68, 1], [.5, 1, 1])


  useEffect(
    () =>
        yRange.onChange((v) => {
            setCurrentPercent(Math.trunc(yRange.current))
        }),
    [yRange]
);


  return (
    <div >
      <Head>
        <title>Bevan Tony Medrano</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      <main className={styles.main}>
        <div> 
        <motion.div exit={{opacity:0}} initial='hidden' animate='visible' variants={{
          hidden:{
            scale:.5,
            opacity:0
          },
          visible:{
            opacity:1,
            scale:1,
            transition:{
              delay:.5
            }
          }
        }}>
          </motion.div>
          <Landing/>
        </div>
      </main>


    </div>
    </div>
  )
}
